Add "force" input (#80)
- Add "force" and "github-token" inputs
- Add "installed" output

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -4,39 +4,100 @@ name: Functional Tests
 on: # yamllint disable-line rule:truthy
   push:
     branches:
-      - "main"
+      - main
   pull_request:
+    paths:
+      - .github/workflows/functional-tests.yml
+      - src/**
+      - action.yml
+  schedule:
+    # Every Friday at 09:00 JST
+    - cron: "0 0 * * 5"
+  workflow_dispatch: {}
+
+defaults:
+  run:
+    shell: sh
 
 jobs:
-  functional_tests:
+  get-versions:
+    name: Get 3 latest versions
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    outputs:
+      versions: ${{ steps.prepare-list.outputs.versions }}
+    steps:
+      - name: Prepare list
+        id: prepare-list
+        env:
+          RELEASES_AMOUNT: "3"
+          TARGET_PIP_PACKAGE: "brainfucky"
+        run: |
+          versions=$(curl -s "https://pypi.org/pypi/${TARGET_PIP_PACKAGE}/json" \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '.releases | keys | .[-($n | tonumber):] | . += ["latest"]')
+          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
+  run-script:
     name: Run script
+    needs: [get-versions]
+    runs-on: ${{ matrix.os }}-latest
     timeout-minutes: 5
     strategy:
       fail-fast: false
       matrix:
         os: ["ubuntu", "windows", "macos"]
-        version: ["0.1.dev0", "0.1.dev1"]
-    runs-on: ${{ matrix.os }}-latest
+        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
     steps:
-      - uses: actions/checkout@v4
-      - uses: ./
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup brainfuck
+        id: setup-brainfuck
+        uses: ./
         with:
-          version: ${{ matrix.version }}
-      - name: Validate command (Linux, macOS)
-        if: ${{ runner.os != 'Windows' }}
+          version: "${{ matrix.version }}"
+      - name: Test action completion
         run: |
-          touch ./hello-world.bf
-          echo "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++" > ./hello-world.bf
-          echo "+.------.--------.>>+.>++." >> ./hello-world.bf
-          output=$(brainfucky --file ./hello-world.bf)
-          rm ./hello-world.bf
-          [[ "${output:32:12}" == "Hello World!" ]] || exit 1;
-        shell: bash
-      - name: Validate command (Windows)
-        if: ${{ runner.os == 'Windows' }}
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "setup-brainfuck should be installed" \
+            "${{ steps.setup-brainfuck.outputs.installed }}" \
+            "true"
+          test_equal "Wrong execution output" \
+            "$(brainfucky --file ./hello-world.bf | sed -n '2p')" \
+            "Hello World!"
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup brainfuck 1
+        id: setup-brainfuck-1
+        uses: ./
+      - name: Setup brainfuck 2
+        id: setup-brainfuck-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
         run: |
-          New-Item -Path . -Name "hello-world.bf" -ItemType "file" -Value "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++`n+.------.--------.>>+.>++."
-          $Output = (brainfucky --file ./hello-world.bf) | Out-String
-          Remove-Item hello-world.bf
-          &{If($Output.Substring(33, 12) -ne 'Hello World!') {exit 1}}
-        shell: pwsh
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-brainfuck-1" \
+            "${{ steps.setup-brainfuck-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-brainfuck-2" \
+            "${{ steps.setup-brainfuck-2.outputs.installed }}" \
+            "${{ matrix.force }}"
